// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHyz1gPdgrFnq-Am56-CdBv1iFG999rsA',
    appId: '1:49454856390:web:a817a3cc11ba0d4a497fc7',
    messagingSenderId: '49454856390',
    projectId: 'dermai-4a57d',
    authDomain: 'dermai-4a57d.firebaseapp.com',
    storageBucket: 'dermai-4a57d.firebasestorage.app',
    measurementId: 'G-MG4N68F7CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjZPJYh1nHkHZDUieAsf7P_iR7Jyph8cA',
    appId: '1:49454856390:android:06b1d878892b8d51497fc7',
    messagingSenderId: '49454856390',
    projectId: 'dermai-4a57d',
    storageBucket: 'dermai-4a57d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv0h_YDwegp796bAHXhJxE4DbP4C9Qy7U',
    appId: '1:49454856390:ios:560075a7e24c093b497fc7',
    messagingSenderId: '49454856390',
    projectId: 'dermai-4a57d',
    storageBucket: 'dermai-4a57d.firebasestorage.app',
    iosClientId: '49454856390-f9kqggrd0tfg168g79g3rf0lpu69j52d.apps.googleusercontent.com',
    iosBundleId: 'com.example.project991',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv0h_YDwegp796bAHXhJxE4DbP4C9Qy7U',
    appId: '1:49454856390:ios:560075a7e24c093b497fc7',
    messagingSenderId: '49454856390',
    projectId: 'dermai-4a57d',
    storageBucket: 'dermai-4a57d.firebasestorage.app',
    iosClientId: '49454856390-f9kqggrd0tfg168g79g3rf0lpu69j52d.apps.googleusercontent.com',
    iosBundleId: 'com.example.project991',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHyz1gPdgrFnq-Am56-CdBv1iFG999rsA',
    appId: '1:49454856390:web:3720de48f81f8290497fc7',
    messagingSenderId: '49454856390',
    projectId: 'dermai-4a57d',
    authDomain: 'dermai-4a57d.firebaseapp.com',
    storageBucket: 'dermai-4a57d.firebasestorage.app',
    measurementId: 'G-87B78JMGNT',
  );

}