name: derm_ai
description: AI-powered skin disease detection app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  tflite_flutter: ^0.11.0
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  image: ^4.0.15
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/DermAI.png"
flutter:
  uses-material-design: true
  assets:
      - assets/models/model_int8_v2.tflite
      - assets/DermAI.png
      - assets/models/discriminator_int8.tflite
      - assets/models/feature_extractor_int8.tflite
      - assets/models/generator_int8.tflite